version: '2'

services:
  dev_db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: express-ts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - express-ts_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 3
  dev_app:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    ports:
      - 3000:3000
      - 9229:9229
    working_dir: /app
    entrypoint: [ '/bin/bash', '-c' ]
    command: [ 'npm start' ]
    volumes:
      - ./:/app
    depends_on:
      - dev_db

volumes:
  express-ts_volume:
